version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-file-monitor
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - N8N_LOG_LEVEL=info
    volumes:
      # Persistent data for n8n
      - ./n8n-data:/home/node/.n8n
      # Mount monitored folder for file detection
      - ../monitored-folder:/app/monitored-folder:ro
      # Mount scripts folder for execution
      - ../scripts:/app/scripts:ro
    working_dir: /home/node/.n8n